// The worker's entry point (wrangler.jsonc "main"): OpenNext's generated
// worker, plus a daily cron for the yearly renewal reminders
// (docs/paypal-plan.md, phase 6b). The cron calls the app's own protected
// route through OpenNext's handler, so it runs exactly like a request (same
// settings, same database client), not as separate code.

// @ts-ignore: generated by `opennextjs-cloudflare build`, resolved by wrangler.
import { default as handler } from "./.open-next/worker.js";

type Env = { CRON_SECRET?: string };
type Ctx = { waitUntil(promise: Promise<unknown>): void };

export default {
  fetch: handler.fetch,

  async scheduled(_controller: unknown, env: Env, ctx: Ctx) {
    const request = new Request("https://alphabes.com/api/cron/renewal-reminders", {
      method: "POST",
      headers: { authorization: `Bearer ${env.CRON_SECRET ?? ""}` },
    });
    ctx.waitUntil(
      handler.fetch(request, env, ctx).then(async (res: Response) => {
        console.log(`renewal reminders: ${res.status} ${await res.text()}`);
      }),
    );
  },
};

// OpenNext's Durable Object classes must be exported by the entry point.
// @ts-ignore: generated by `opennextjs-cloudflare build`, resolved by wrangler.
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";
