// Titles and descriptions rewritten for search (docs/seo-batch2-proposals.md,
// approved 2026-10-07), keyed by the page's path. Only the <title>, the meta
// description and the og/twitter tags change: the text on the page, and the
// data it's built from, stay as they are. Applied by withSocialMetadata
// (lib/social-metadata.ts); tests/seo/meta-overrides.test.ts checks that every
// path is a real page and every text fits within Google's limits.
export type MetaOverride = { title?: string; description?: string };

const PAGES: Record<string, MetaOverride> = {
  // English
  "/activities": { title: "Hands-On Alphabet and Phonics Activities", description: "Simple alphabet activities to pair with any letter lesson: find and circle letters, trace, sort pictures by first sound, and color by letter." },
  "/alphabet": { description: "Learn the alphabet from A to Z: letter names and sounds, uppercase and lowercase, words to hear, tracing, and free printable worksheets." },
  "/blog/alphabet": { description: "Articles for parents and teachers on teaching letter names, letter shapes and letter recognition, with simple ideas to try at home." },
  "/blog/fun-abc-games-for-kids": { description: "Simple ABC games that turn alphabet practice into play: I Spy with letters, letter card matching, letter races and movement games." },
  "/blog/how-to-practice-phonics-at-home": { description: "Everyday routines that build phonics skills without extra flashcards: reading aloud together, rhyming games in the car or bath, short sessions." },
  "/blog/how-to-teach-the-alphabet-to-preschoolers": { description: "How to teach the alphabet to a 3 or 4 year old: simple, low-pressure ways to introduce letters, which letters to start with, and why." },
  "/blog/kindergarten": { description: "Articles on kindergarten letters, phonics and writing: what children learn at 5 and 6, and how parents can help at home." },
  "/blog/learning-activities": { description: "Games and activity ideas for early learners: quick, hands-on ways to practice letters and sounds at home or in class." },
  "/blog/phonics": { description: "Articles on phonics for parents: letter sounds, blending, CVC words and early reading, with a simple timeline and ideas to try." },
  "/blog/preschool-activities": { description: "Hands-on preschool activity ideas for ages 3 to 5: letters, sounds and fine motor play, with little preparation needed." },
  "/blog/worksheets": { description: "How to choose and use printable worksheets for preschool and kindergarten: what to look for, how often, and how to keep it fun." },
  "/contact": { description: "Questions, ideas or a problem with a worksheet? Write to the AlphaBes team and we'll get back to you as soon as we can." },
  "/flashcards": { title: "Alphabet Flashcards: A to Z Picture Words" },
  "/games": { title: "Alphabet Games for Kids: Letters and Sounds" },
  "/games/alphabet-quiz": { title: "Alphabet Quiz: Letter Names and Sounds Game" },
  "/games/beginning-sound": { title: "Beginning Sounds Game: Hear the First Sound" },
  "/games/find-the-letter": { title: "Find the Letter: Free Alphabet Game for Kids" },
  "/games/letter-tracing": { title: "Letter Tracing Game: Trace A to Z on Screen" },
  "/games/match-letter-picture": { title: "Match the Letter and Picture: Free Phonics Game" },
  "/kindergarten": { title: "Kindergarten Activities: Sight Words and Writing", description: "Kindergarten activities from AlphaBes: sight words, writing letters without tracing, and phonics, with worksheets and games for ages 5 to 6." },
  "/kindergarten/handwriting": { description: "Kindergarten handwriting: from tracing to writing letters on their own, with tips on letter size, spacing and where each letter starts." },
  "/phonics": { description: "Phonics for kids: letter sounds, beginning sounds, CVC words, blending and word families, with examples, games and printable worksheets." },
  "/phonics/beginning-sounds": { title: "Beginning Sounds: Hear the First Sound in a Word", description: "Beginning sounds: help your child hear the first sound in a word, like /b/ in ball, with listening games and picture activities." },
  "/phonics/blending": { title: "Blending Sounds: How Kids Learn to Read Words", description: "Blending sounds turns c-a-t into cat. How to teach blending step by step, with example words and short games to play at home." },
  "/phonics/cvc-words": { title: "CVC Words for Kids: Read Your First Words", description: "CVC words like cat, pig and sun are a child's first readable words. Learn how to sound them out, with examples and practice ideas." },
  "/phonics/letter-sounds": { title: "Letter Sounds for Kids: A to Z with Examples", description: "Letter sounds for kids: the sound each letter makes from A to Z, with example words and simple ways to practice them at home." },
  "/phonics/long-vowels": { title: "Long Vowel Sounds for Kids: Cake, Bike, Boat", description: "Long vowels say their own name, like a in cake or o in boat. Examples, the silent e pattern, and when to teach long vowel sounds." },
  "/phonics/segmenting": { title: "Segmenting: Break a Word into Its Sounds", description: "Segmenting means breaking a word into its sounds, like map into /m/ /a/ /p/. Why it matters for spelling, with examples and games." },
  "/phonics/short-vowels": { title: "Short Vowel Sounds for Kids: a, e, i, o, u", description: "The short vowel sounds of a, e, i, o and u, as in apple, bed, pig, hot and sun, with example words and tips for early readers." },
  "/phonics/word-families": { title: "Word Families for Kids: -at, -ig, -un and More", description: "Word families like -at, -ig and -un help kids read new words fast: cat, hat, mat. Lists of examples and ways to practice them." },
  "/preschool": { description: "Preschool activities from AlphaBes: letter recognition, tracing, coloring and first sounds, with free worksheets and games for ages 3 to 5." },
  "/pricing": { title: "AlphaBes Pro: Plans and Pricing", description: "Compare the AlphaBes Free and Pro plans. Pro is $7.99 a month or $59 a year and adds the premium games and whole-bundle downloads." },
  "/stories": { title: "Short Stories for Kids to Read and Listen To", description: "Eight short illustrated stories for children ages 3 to 7 to read together or listen to: a little red apple, a brave bear, a curious cat and more." },
  "/worksheets": { description: "Free printable alphabet worksheets for every letter A to Z: tracing, uppercase, lowercase, recognition, beginning sounds, coloring and more." },
  "/worksheets/alphabet": { description: "Alphabet worksheets for every letter from A to Z: recognize, trace and write each letter in uppercase and lowercase. Free printable PDFs." },
  "/worksheets/alphabet-writing-practice": { description: "Writing practice for each letter: rows of the uppercase and lowercase letter to trace on ruled lines, then a word. One page per letter." },
  "/worksheets/beginning-sounds": { description: "Beginning sounds worksheets: circle the pictures that start with each letter's sound, from A to Z. Free printable PDFs for pre-K." },
  "/worksheets/bundles": { title: "Alphabet Worksheet Bundles: A to Z in One PDF" },
  "/worksheets/coloring": { description: "Letter coloring pages from A to Z: a big outline letter and a picture that starts with it, to color and say aloud. Free printable PDFs." },
  "/worksheets/colors": { title: "Color Worksheets for Preschool (Free PDF)", description: "Color worksheets for preschool: ten colors to recognize, color in and name, one page per color. Free printable PDFs to print at home." },
  "/worksheets/cvc-words": { description: "CVC word worksheets: read, trace and write simple words like cat, dog and sun, one word per page. Free printable PDFs for kindergarten." },
  "/worksheets/handwriting": { description: "Handwriting worksheets for every letter from A to Z: practice the uppercase and lowercase letter neatly on ruled lines. Free printable PDFs." },
  "/worksheets/letter-coloring": { description: "Coloring pages with a big outline letter and a picture that starts with it, to link each letter to a word. One page per letter, A to Z." },
  "/worksheets/letter-cursive": { description: "Cursive letter worksheets from A to Z: trace the uppercase and lowercase cursive letter and a word, then write them. Free printable PDFs." },
  "/worksheets/letter-recognition": { description: "Letter recognition worksheets: find and circle every matching letter in a grid of look-alike letters. One page per letter, A to Z." },
  "/worksheets/letter-tracing": { description: "Letter tracing worksheets with large dotted uppercase and lowercase letters, practice rows and space to write. One per letter, A to Z." },
  "/worksheets/numbers": { description: "Number tracing worksheets from 0 to 9: trace each number and its name, count the stars, then write it on your own. Free printable PDFs." },
  "/worksheets/numbers-cursive": { description: "Cursive number worksheets from 0 to 9: trace each number and its name in cursive, count, then write it on your own. Free printable PDFs." },
  "/worksheets/phonics": { title: "Phonics Worksheets for Kindergarten (Free PDF)", description: "Phonics worksheets for every letter: letter sounds, beginning sounds and blending practice pages for pre-K and kindergarten. Free PDFs." },
  "/worksheets/shapes": { description: "Shape tracing worksheets: circle, square, triangle, star, heart and more, one shape per page to trace and name. Free printable PDFs." },
  "/worksheets/sight-words": { description: "Sight word worksheets for the first words kids read: a, and, I, in, is, it, the, to, was, you. Read, trace and write. Free PDFs." },
  "/worksheets/tracing": { title: "Tracing Worksheets for Preschool and Pre-K", description: "Tracing worksheets for preschool and pre-K: guided pages for every letter A to Z to build pencil control and letter shapes. Free PDFs." },
  // French
  "/fr/activites": { description: "Huit activités faciles à la maison ou en classe : chasse aux lettres, pâte à modeler, plateau de semoule, loto, mémory… De la PS au CP." },
  "/fr/alphabet": { description: "L'alphabet de A à Z : le nom et le son de chaque lettre, des mots illustrés à écouter, les accents et des fiches de tracé en script et en cursive." },
  "/fr/alphabet/accents": { description: "Les accents expliqués aux enfants : ceux qui changent le son (é, è, ê, ç), ceux qui ne le changent pas (à, ù, â, î…), le tréma et le e dans l'o." },
  "/fr/contact": { description: "Une question, une suggestion ou un souci avec une fiche ? Écrivez à l'équipe AlphaBes, nous vous répondons au plus vite." },
  "/fr/cookies": { description: "Les cookies utilisés par AlphaBes, à quoi ils servent et comment accepter, refuser ou modifier vos choix à tout moment." },
  "/fr/fiches": { title: "Fiches à imprimer gratuites : alphabet, cursive, sons", description: "238 fiches gratuites en PDF pour la maternelle et le CP : tracé des lettres, cursive sur Seyès, sons, syllabes, nombres, formes et couleurs." },
  "/fr/fiches/formes": { description: "Rond, carré, triangle, étoile… des fiches pour repasser les formes et écrire leur nom. Gratuites, à imprimer, pour la maternelle." },
  "/fr/fiches/packs": { description: "Plusieurs fiches dans un seul PDF : l'alphabet complet, toutes les fiches d'une lettre, ou un type de fiche de A à Z. Maternelle et CP." },
  "/fr/grande-section": { title: "Grande section : lettres, syllabes et cursive (5-6 ans)", description: "Les lettres, les syllabes, les premiers mots-outils et l'écriture cursive : idées, jeux et fiches pour la grande section, avant le CP." },
  "/fr/histoires": { description: "Huit petites histoires illustrées pour les 3-7 ans, à lire ensemble ou à écouter : une pomme, un ourson, un chat curieux, un lion qui fait la sieste…" },
  "/fr/histoires/moustache-le-chat-curieux": { title: "Moustache, le chat curieux : histoire à lire et à écouter" },
  "/fr/jeux": { description: "Cinq jeux pour la maternelle et le CP, dont deux gratuits : trouver une lettre, l'associer à une image, le premier son, le tracé et un quiz." },
  "/fr/jeux/lettre-et-image": { title: "Associe la lettre et l'image : jeu gratuit" },
  "/fr/jeux/quiz-alphabet": { title: "Le quiz de l'alphabet : jeu pour apprendre les lettres" },
  "/fr/jeux/trouve-la-lettre": { title: "Trouve la lettre : jeu gratuit pour apprendre les lettres" },
  "/fr/maternelle": { title: "Maternelle : apprendre les lettres en PS et MS (3-5 ans)", description: "Graphisme, tracé des lettres en capitales, coloriage et premiers sons : idées et fiches pour accompagner un enfant de PS et MS à la maison." },
  "/fr/maternelle/coloriage": { title: "Coloriage des lettres en maternelle : l'alphabet à colorier" },
  "/fr/maternelle/tracer-les-lettres": { title: "Tracer les lettres en maternelle : les capitales d'abord" },
  "/fr/sons": { title: "Les sons du français : apprendre à lire, maternelle et CP", description: "Les voyelles, la syllabe, puis ou, on, an, in, oi, ch… Des pages à écouter, des mots illustrés, une phrase à lire et un jeu, pour apprendre à lire." },
  "/fr/sons/e-accent-aigu": { description: "Le son [e] de bébé, qui s'écrit é, et aussi er ou ez à la fin des mots : des mots illustrés à écouter, une phrase à lire et un jeu." },
  "/fr/sons/e-accent-grave": { description: "Le son [ɛ] de chèvre, de forêt, de fraise et de reine, qui s'écrit è, ê, ai ou ei : des mots à écouter, une phrase à lire et un jeu." },
  "/fr/sons/eu": { description: "Le son [ø] de feu, de fleur et de cœur, qui s'écrit eu ou œu : des mots illustrés à écouter, une phrase à lire et un petit jeu (CP)." },
  "/fr/sons/gn": { description: "g et n ensemble font [ɲ], le son de champignon et de montagne : des mots illustrés à écouter, une phrase à lire et un petit jeu (CP)." },
  "/fr/sons/ill": { title: "Le son ill (ill, ail, eil, euil, ouil) : mots et exercice" },
  "/fr/sons/in": { description: "Le son [ɛ̃] de lapin, de main et de pain, qui s'écrit in, im, ain ou ein : des mots à écouter, une phrase à lire et un petit jeu (CP)." },
  "/fr/sons/lettres-muettes": { title: "Les lettres muettes : le h, les consonnes finales, le e muet" },
  "/fr/sons/o-au-eau": { description: "Le son [o] s'écrit o, au ou eau : vélo, auto, bateau. Des mots illustrés à écouter, une phrase à lire et un petit jeu, pour le CP." },
  "/fr/sons/oi": { description: "o et i ensemble font [wa], comme dans roi et étoile : des mots illustrés à écouter, une phrase à lire et un petit jeu, pour le CP." },
  "/fr/sons/on": { description: "Le son [ɔ̃] de ballon et de pont, qui s'écrit on, ou om devant b et p : des mots à écouter, une phrase à lire et un petit jeu (CP)." },
  "/fr/tarifs": { title: "AlphaBes Pro : formules et tarifs" },
  // Spanish
  "/es": { description: "Fichas gratis para imprimir, trazo de letras, sílabas y primeras lecturas para preescolar y primaria. Juegos y lecciones para niños de 3 a 8 años." },
  "/es/abecedario": { title: "El abecedario para niños: las 27 letras y sus sonidos", description: "El abecedario de la A a la Z, con la Ñ: el nombre y el sonido de cada letra, sus sílabas, palabras con dibujos y el trazo en script y cursiva." },
  "/es/abecedario/tilde": { title: "La tilde y la diéresis explicadas a los niños" },
  "/es/actividades": { title: "Actividades para aprender letras y sílabas, sin pantallas", description: "Ocho actividades fáciles para la casa o el salón: buscar letras, plastilina, la bandeja de sal, «Veo, veo» con sílabas, bingo y memoria. De 3 a 7 años." },
  "/es/contacto": { description: "¿Tienes una pregunta, una sugerencia o un problema con una ficha? Escribe al equipo de AlphaBes y te respondemos lo antes posible." },
  "/es/cookies": { description: "Las cookies que usa AlphaBes, para qué sirven y cómo aceptar, rechazar o cambiar tus preferencias en cualquier momento." },
  "/es/cuentos": { description: "Ocho cuentos cortos ilustrados para niños de 3 a 7 años, para leer juntos o escuchar: una manzanita, un osito valiente, una gatita curiosa…" },
  "/es/fichas": { title: "Fichas para imprimir gratis: abecedario, cursiva y sílabas", description: "239 fichas gratis en PDF para preescolar y primaria: trazo de letras, cursiva en doble raya, sílabas, números en cuadrícula, figuras y colores." },
  "/es/fichas/paquetes": { description: "Varias fichas en un solo PDF: el abecedario completo, todas las fichas de una letra, las sílabas o un tipo de ficha de la A a la Z." },
  "/es/juegos": { description: "Seis juegos para preescolar y primer grado, tres gratis: encontrar letras, la letra y su dibujo, la primera sílaba, trazar, un quiz y aplaudir sílabas." },
  "/es/juegos/aplaude-las-silabas": { title: "Aplaude las sílabas: juego gratis para aprender a leer" },
  "/es/juegos/encuentra-la-letra": { title: "Encuentra la letra: juego gratis para aprender a leer" },
  "/es/juegos/letra-y-dibujo": { title: "La letra y el dibujo: juego gratis para aprender a leer" },
  "/es/juegos/primera-silaba": { title: "¿Con qué sílaba empieza?: juego para aprender a leer" },
  "/es/kinder/silabas": { title: "Las sílabas en kínder: aplaudir, contar y unir" },
  "/es/precios": { title: "AlphaBes Pro: planes y precios" },
  "/es/preescolar": { title: "Preescolar: actividades para aprender las letras (3-5 años)" },
  "/es/preescolar/colorear": { title: "Colorear las letras en preescolar: el abecedario" },
  "/es/preescolar/traza-las-letras": { title: "Trazar las letras en preescolar: primero su nombre" },
  "/es/preescolar/trazos": { title: "Trazos para preescolar: grafomotricidad para escribir" },
  "/es/silabas": { title: "Las sílabas: aprender a leer con el método silábico", description: "Las vocales, las sílabas directas (ma, me, mi, mo, mu), inversas, mixtas y trabadas, y los casos especiales: ch, ll, rr, que, gue, la h muda." },
  "/es/silabas/palabras-frecuentes": { title: "Palabras frecuentes para leer de corrido: el, la, un, y" },
  "/es/silabas/silabas-mixtas": { title: "Sílabas mixtas (cerradas): sol, pan, mar, con palabras" },
  "/es/silabas/trabadas-con-l": { title: "Sílabas trabadas con l: bla, cla, fla, gla, pla" },
  // Portuguese
  "/pt": { description: "Atividades de alfabetização grátis para imprimir, traçado, famílias silábicas e primeiras leituras. Jogos e lições para crianças de 3 a 8 anos." },
  "/pt/alfabeto": { title: "O alfabeto para crianças: as 26 letras e os sons", description: "O alfabeto de A a Z, com o Ç: o nome e o som de cada letra, a família silábica, palavras com figuras e o traçado em bastão, forma e cursiva." },
  "/pt/alfabeto/acentos": { title: "Os acentos e o til explicados para crianças" },
  "/pt/atividades": { title: "Atividades para imprimir grátis: alfabeto, cursiva, sílabas", description: "272 atividades grátis em PDF para a educação infantil e o 1º ano: letra bastão, de forma e cursiva, famílias silábicas, números, formas e cores." },
  "/pt/atividades/cores": { description: "Dez cores para reconhecer: colorir a figura com a cor certa e escrever o nome da cor. Atividades grátis em PDF para imprimir." },
  "/pt/atividades/pacotes": { description: "Várias atividades num só PDF: o alfabeto completo, todas as atividades de uma letra, as famílias silábicas ou um tipo de atividade." },
  "/pt/atividades/reconhecer-letras": { description: "Achar a letra nos quatro tipos de letra, entre letras parecidas: uma atividade por letra, de A a Z. Grátis, em PDF para imprimir." },
  "/pt/brincadeiras": { description: "Oito brincadeiras fáceis em casa ou na escola: procurar letras, massinha, bandeja de sal, “Eu vejo” com sílabas, bingo e memória. De 3 a 7 anos." },
  "/pt/contato": { description: "Tem uma pergunta, uma sugestão ou um problema com uma atividade? Escreva para a equipe do AlphaBes e respondemos o quanto antes." },
  "/pt/cookies": { description: "Os cookies que o AlphaBes usa, para que servem e como aceitar, recusar ou mudar as suas preferências a qualquer momento." },
  "/pt/educacao-infantil": { title: "Educação infantil: atividades com as letras (3 a 5 anos)" },
  "/pt/educacao-infantil/colorir": { title: "Colorir as letras na educação infantil: o alfabeto" },
  "/pt/educacao-infantil/coordenacao-motora": { title: "Coordenação motora fina: preparar a mão para escrever" },
  "/pt/educacao-infantil/tracar-as-letras": { title: "Traçar as letras: primeiro o nome, em letra bastão" },
  "/pt/historias": { description: "Oito histórias curtas ilustradas para crianças de 3 a 7 anos, para ler juntos ou ouvir: uma maçãzinha, um ursinho corajoso, uma gatinha…" },
  "/pt/jogos": { description: "Seis jogos para a educação infantil e o 1º ano, três grátis: encontrar letras, letra e figura, sílaba inicial, traçado, quiz e bater palmas." },
  "/pt/jogos/letra-e-figura": { title: "A letra e a figura: jogo grátis para aprender a ler" },
  "/pt/precos": { title: "AlphaBes Pro: planos e preços" },
  "/pt/primeiro-ano": { title: "1º ano: famílias silábicas, leitura e letra cursiva", description: "As famílias silábicas, as primeiras palavras e frases, as palavras frequentes e a letra cursiva: ideias, jogos e atividades para os 6 anos." },
  "/pt/primeiro-ano/familias-silabicas": { title: "Famílias silábicas no 1º ano: como ajudar em casa" },
  "/pt/primeiro-ano/palavras-frequentes": { title: "Palavras frequentes no 1º ano: ler com fluência" },
  "/pt/silabas": { description: "As vogais, os encontros vocálicos, as famílias silábicas, os dígrafos (ch, lh, nh, rr, ss, qu, gu), os sons nasais e as sílabas complexas." },
  "/pt/silabas/ar-er-ir-or-ur": { title: "O R no fim da sílaba: ar, er, ir, or, ur" },
  "/pt/silabas/as-es-is-os-us": { title: "O S no fim da sílaba: as, es, is, os, us" },
  "/pt/silabas/encontros-com-r": { title: "Encontros consonantais com R: bra, cra, pra, tra" },
  "/pt/silabas/encontros-vocalicos": { title: "Encontros vocálicos: ai, ei, oi, ou, au, eu, ui" },
  "/pt/silabas/palavras-frequentes": { title: "Palavras frequentes para ler com fluência: o, a, um, e" },
};

// English letter bundles: one description pattern for the 26 letters (rule R4).
for (const l of "abcdefghijklmnopqrstuvwxyz") {
  PAGES[`/worksheets/bundles/letter-${l}-bundle`] = {
    description: `All 10 worksheet types for the letter ${l.toUpperCase()}${l} in one PDF: tracing, recognition, beginning sounds, coloring, matching, writing and review.`,
  };
}

export const META_OVERRIDES: Readonly<Record<string, MetaOverride>> = PAGES;
