import type { Locale } from "@/i18n/routing";
import { getAtividadePack } from "@/lib/atividades-pt";
import { getFichaPack } from "@/lib/fichas-es";
import { getFichePack } from "@/lib/fiches-fr";
import { getBundleBySlug } from "@/lib/worksheet-bundles";

// Whole-bundle PDFs are a Pro download (docs/paypal-plan.md, B4). They live
// in pro-files/<locale>/<slug>.pdf in the repo (generated by npm run
// bundles:en, fiches:fr, fichas:es, atividades:pt), are uploaded with the
// same keys to the private R2 bucket alphabes-pro-files, and are served only
// by app/api/bundles/[locale]/[slug] after a Pro check. Never from public/.

export const PRO_FILES_DIR = "pro-files";

export function bundleExists(locale: Locale, slug: string): boolean {
  switch (locale) {
    case "fr":
      return !!getFichePack(slug);
    case "es":
      return !!getFichaPack(slug);
    case "pt":
      return !!getAtividadePack(slug);
    default:
      return !!getBundleBySlug(slug);
  }
}

// The file's key in the bucket, and its path under pro-files/.
export function bundleKey(locale: Locale, slug: string): string {
  return `${locale}/${slug}.pdf`;
}

// Where the download button points.
export function bundleDownloadUrl(locale: Locale, slug: string): string {
  return `/api/bundles/${locale}/${slug}`;
}

// What the download sends: a file body (stream or bytes) and its size.
export type ProFile = { body: ReadableStream | Uint8Array; size: number };

type R2Like = { get(key: string): Promise<{ body: ReadableStream; size: number } | null> };

// Reads a Pro file: from the PRO_FILES R2 binding on Cloudflare, or, under
// `next dev` (no Cloudflare bindings on this Windows machine), from the local
// pro-files/ folder.
export async function readProFile(key: string): Promise<ProFile | null> {
  let bucket: R2Like | undefined;
  try {
    const { getCloudflareContext } = await import("@opennextjs/cloudflare");
    bucket = (getCloudflareContext().env as { PRO_FILES?: R2Like }).PRO_FILES;
  } catch {
    // Not running on Cloudflare.
  }
  if (bucket) {
    const object = await bucket.get(key);
    return object ? { body: object.body, size: object.size } : null;
  }
  if (process.env.NODE_ENV === "development") {
    const { readFile } = await import("node:fs/promises");
    const { join } = await import("node:path");
    try {
      const bytes = await readFile(join(process.cwd(), PRO_FILES_DIR, key));
      return { body: new Uint8Array(bytes), size: bytes.length };
    } catch {
      return null;
    }
  }
  return null;
}
